### PR TITLE
Speed-up building tools

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
@MartyLake: I don't know why `IconBuilder` is failing to build with JUCE 4.2.0 and Xcode 7.3.1... I'll investigate, but please don't spend time reviewing this PR yet. Thanks!

**Comment by McMartin** [comment]
@MartyLake: please review, thanks!

**Comment by McMartin** [comment]
@MartyLake: gentle ping

**Comment by MartyLake** [comment]
@McMartin LGTM!!!

**Pull request merged**
