### PR TITLE
Do not fallback to first configuration when there is only one

### PR DESCRIPTION
**Pull request by McMartin**
@lethal-guitar, @MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
@lethal-guitar, @MartyLake: ping

**Comment by MartyLake** [comment]
I find this PR hard to review on GH. It looks good to me but it's hard to verify the logic changes.

**Comment by McMartin** [comment]
@MartyLake please point me to specific commits or hunks that are difficult to understand and I'll do my best to refactor the changes or expand the commit messages,

**Comment by McMartin** [comment]
@MartyLake: I reworked that PR a bit to make it easier to review. It is now based on top of https://github.com/McMartin/FRUT/pull/314 (to be reviewed first, thanks!) and the last commit has been split into 3.

**Comment by McMartin** [comment]
@MartyLake #314 has been merged, so I rebased this PR on top of `master`. Please have another look, thanks!

**Pull request merged**
