### PR TITLE
Set OSX SDK settings per target and per configuration

### PR DESCRIPTION
**Pull request by McMartin**
@lethal-guitar, @MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
@lethal-guitar, @MartyLake: this PR is now based on top of `master` and ready for review. Please take a look, thanks!

@Xav83: this PR might break things related to OSX SDK root and deployment target. Feel free to try this branch and report any problem, thanks!

**Comment by Xav83** [comment]
Hi @McMartin,

I've tried this PR on our project, with JUCE 5.2.0, on a 10.12 OSX machine. In our Projucer, we have the `OSX Base SDK Version` field sets to `Use Default`, and the `OSX Deployment Target` field sets to `10.9`.
I've checked in XCode, and all the specific target of the plugin that we build (VST, VST3, AU and Standalone) are well set with our `OSX Base SDK Version` and `OSX Deployment Target` fields content, but the targets generated by Cmake (ALL_BUILD, install, zero_check and package) still have their `macOS Deployement Target` set to `macOS 10.12`.

FYI, I've run the same test on the FRUT's `master` branch, and all the target generated in the Xcode solution had their `macOS Deployment Target` field sets to `macOS 10.9`, the value from our jucer file.

**Comment by McMartin** [comment]
@Xav83 thank you very much for trying this PR. I don't think the `Deployment Target` of the ALL_BUILD, install, zero_check and package targets matters, since they are not compiling any code. If you encounter any problem related to these 4 targets having a different `Deployment Target` than the rest, let me ASAP, thanks!

**Comment by Xav83** [comment]
@McMartin The `Deployment target` of ALL_BUILD, install, zero_check and package doesn't seem to trigger any bugs on our project, so far. 😉 👍

**Comment by McMartin** [comment]
@Xav83 great! We just need a review from @lethal-guitar or @MartyLake and we can merge :smile:

**Comment by MartyLake** [comment]
Lgtm 👌

**Pull request merged**
