### PR TITLE
Support the "Suppress AudioUnit Plist resourceUsage Key" setting

### PR DESCRIPTION
**Pull request by McMartin**

### CODE REVIEW

**Comment by McMartin** [comment]
@MartyLake please review (after reviewing https://github.com/McMartin/FRUT/pull/734), thanks!

**Comment by McMartin** [comment]
@MartyLake Thanks a bunch for reviewing #734. I've rebased this PR on top of the latest `main`. Please review, thanks!

**Comment by McMartin** [comment]
@MartyLake gentle ping

**Review by MartyLake — APPROVED** [review]
LGTM !

**Pull request merged**
