### PR TITLE
Make FRUT installable

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
⚠️ GitHub is showing commits sorted by SHA1, which doesn't make any sense in terms of commit order.
The proper order is:
- 9b78ab1
- 760b1c8
- 19bc982
- 3b1eb2a
- c8b7d1e
- 4bbbc91
- a1625b6

**Comment by MartyLake** [comment]
Lgtm!
Should juce headers be "installed" as well?

**Comment by McMartin** [comment]
@MartyLake which headers are you talking about? These are the files that get install currently:
```
-- Install configuration: "Release"
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/Reprojucer.cmake
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/resources.rc
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/PkgInfo
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/JuceHeader-4.h
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/Info.plist
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/AppConfig-4.h
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/JuceLibraryCode-Wrapper.cpp
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/AppConfig.h
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/script.in
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/templates/JuceHeader.h
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/bin/Jucer2Reprojucer
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/bin/BinaryDataBuilder-0.1.0
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/bin/IconBuilder-0.1.0
-- Installing: /home/travis/build/McMartin/FRUT/prefix/FRUT/cmake/bin/PListMerger-0.1.0
```
Which one would be missing?

**Comment by MartyLake** [comment]
The JUCE sources?

**Comment by MartyLake** [comment]
Latest? :-P

That's optional I think.

**Comment by McMartin** [comment]
> That's optional I think.

It's not just optional, it's out of topic. FRUT won't bundle JUCE, nor CMake, nor any C++ compiler.

**Comment by MartyLake** [comment]
Lgtm then

**Pull request merged**
