### PR TITLE
Support compiling .r resource files for AU plugins

### LINKED ISSUE #398: AudioUnit plugin not discoverable
When building an AudioUnit plugin (macOS only) after generating an XCode project using FRUT, the plugin is not discoverable by AU hosts and the Apple validation tool (`auval -a` or `auval -v <type> <plugin> <manufacturer>`).

Generating the same AU plugin using the Projucer does the trick. After some digging, it seems it all boils down to an XCode "Rez" file (or "Carbon resource") not being copied (nor compiled) from JUCE:

```bash
juce/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU.r -> JuceLibraryCode/include_juce_audio_plugin_client_AU.r
```

I tried to simply modify FRUT to discover `.r` files in JUCE modules, which adds it properly only to the AU building group, in `jucer_project_module`:

```cmake
  file(GLOB module_src_files
    LIST_DIRECTORIES FALSE
    "${modules_folder}/${module_name}/${module_name}*.cpp"
    "${modules_folder}/${module_name}/${module_name}*.mm"
    "${modules_folder}/${module_name}/${module_name}*.r"
  )
```

However, something more seems to be required in order to properly build the "Rez" file (i.e. make XCode know it is a "Rez" file and not just a "Source file", add it to the AU building target, and compile it using Reztool) and add it to the final bundle `.component`.

Any ideas?

Also if there is a simple trick to bypass the Rez file all-together and make AU plugins discoverable in a deterministic fashion, this is very welcome!

### PR DESCRIPTION
**Pull request by McMartin**
Resolves #398.
Supersedes and closes #399.

@MartyLake: please review, thanks!
@rclement: please confirm that it works for you, thanks!

### CODE REVIEW

**Comment by rclement** [comment]
@McMartin Works for me! Thanks for the cleanup!

**Comment by McMartin** [comment]
@MartyLake, @rclement: calling `Rez` when using the Xcode generator was actually failing, so I rebased the branch and added 2 commits to fix the issue.

**Comment by rclement** [comment]
@McMartin Sorry to come back to this PR but, what exactly did you change in the latest rework of this PR last Friday? (the diff cannot be seen as it has been rebased)

The merged version on `master` works great on MacOS 10.12 with XCode 9.
But I am told that the `Rez` command does not build on MacOS 10.14 using XCode 10 with the following error:

```bash
juce/modules/juce_audio_plugin_client/juce_audio_plugin_client_AU.r:28: ### /Applications/Xcode.app/Contents/Developer/usr/bin/Rez - SysError 2 during open of "AudioUnit/AudioUnit.r".
Fatal Error!
```

It was working fine on 10.14 last Thursday using the `support-compiling-resource-files-for-AU-plugins` branch (as stated first when this PR was created).

FYI, building a JUCE test plugin on MacOS 10.14 builds properly with `Rez` (the Projucer generated Rez command is still the same, not 10.14-specific stuff).

Please let me know if I can help in anyway.

**Comment by McMartin** [comment]
@rclement when I opened the PR, the HEAD commit was https://github.com/McMartin/FRUT/commit/f153c07ae448c7eae917b304571ec4fc027beda6 and the "fake" merge commit was https://github.com/McMartin/FRUT/commit/3d753122fca10810b4b00a07491c0d7beea9a238.

After I rebased, the HEAD commit became https://github.com/McMartin/FRUT/commit/7d19d9b27a066cf5897f7c257ac40030a8805fb7 and the "fake" merge commit was https://github.com/McMartin/FRUT/commit/97c3ba2692ed243922862eccc104f419b8ac8eb4.

When comparing [`f153c07..7d19d9b`](https://github.com/McMartin/FRUT/compare/f153c07ae448c7eae917b304571ec4fc027beda6..7d19d9b27a066cf5897f7c257ac40030a8805fb7) or [`3d75312..97c3ba2`](https://github.com/McMartin/FRUT/compare/3d753122fca10810b4b00a07491c0d7beea9a238..97c3ba2692ed243922862eccc104f419b8ac8eb4), we get the same diff, but I really don't see what could explain the difference of behavior between macOS 10.12 and macOS 10.14 in that diff.

Are you sure it wasn't your branch (https://github.com/McMartin/FRUT/pull/399 / 50b310cb388a868cbf4b151ee4a66e02bb367577) that worked on on macOS 10.14?

**Comment by rclement** [comment]
@McMartin Thanks for the feedback.

After re-checking with the other developer, indeed it was building fine last Thursday but using my branch #399.

Some more testing showed the key difference resides in the missing `-isysroot` argument to `Rez`, such as:

```cmake
          add_custom_command(TARGET ${au_target} PRE_BUILD
            COMMAND
            "${Rez_tool}"
            "-o" "${rez_output}"
            "-d" "SystemSevenOrLater=1"
            "-useDF"
            "-isysroot" "${CMAKE_OSX_SYSROOT}"
            ${rez_defines}
            ${rez_archs}
            "-i" "${carbon_include_dir}"
            "-i" "${CMAKE_CURRENT_BINARY_DIR}/JuceLibraryCode"
            "-i" "${juce_audio_plugin_client_include_dir}"
            ${rez_inputs}
          )
```

It seems that some Apple Frameworks are "broken" in `/System/Library/Frameworks` and need to be fetched from `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.<version>.sdk/System/Library`.
Specifically to the problem, the `AudioUnit.framework` is empty in `/System/Library/Frameworks` and all the necessary headers and resources (e.g. `AudioUnit/AudioUnit.r`) are only to be found in the "OSX sysroot".

FYI, the `-isysroot` argument does not make a difference on 10.12 though, it compiles fine in with or without it.

The change is simple enough so I made PR #402 to fix the issue.

**Pull request merged**
