### PR TITLE
Improve workflow in case of build failure

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
Note to self: when merging this PR, the following issues should be reworded: #512, #513, #514, and #515.

**Comment by MartyLake** [comment]
LGTM :D

**Comment by McMartin** [comment]
@MartyLake: I rebased this PR on top of the latest `master` and reworked it to improve the workflow even more. All commits have changed or are new, so please make a new review, thanks!

**Comment by MartyLake** [comment]
Even better! LGTM!

**Pull request merged**
