### PR TITLE
Improve fatal error message about absolute path

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake, @scotchi: please review, thanks!

### CODE REVIEW

**Comment by scotchi** [comment]
Seems fine -- but is there a particular reason *not* to assume that `${CMAKE_CURRENT_SOURCE_DIR}` is the project root?  If you're not building JUCE itself, are there common cases where you wouldn't want that?

**Comment by McMartin** [comment]
I had to re-read the CMake documentation to refresh my understanding of `CMAKE_CURRENT_LIST_DIR` vs. `CMAKE_CURRENT_SOURCE_DIR` vs. `CMAKE_SOURCE_DIR`. While doing so I realized that depending on the project structure, someone might want `Reprojucer.cmake` to assume that the project root is any of them, or even something else.
Being explicit about the value of `JUCER_PROJECT_DIR` should prevent subtle bugs, especially when moving/merging/splitting CMakeLists.txt files.

**Comment by scotchi** [comment]
I suppose I'm coming from a more CMake-y background (though I realize reading over my changes that I'm somewhat rusty there too).  To me felt natural to have `jucer_project_files(...sources...)` assume the same things as `add_library(...sources...)` about their paths.  (And in my case, that's exactly what I was porting things from.)

I don't actually care very much about this -- it just felt weird having to be explicit about the source root when using Reprojucer when you wouldn't normally have to with CMake.

**Comment by McMartin** [comment]
> To me felt natural to have `jucer_project_files(...sources...)` assume the same things as `add_library(...sources...)` about their paths.

> it just felt weird having to be explicit about the source root when using Reprojucer when you wouldn't normally have to with CMake.

@scotchi these are very good points, and I agree with you. So I opened #351 and closing this PR in its favor.

**Pull request closed without merging**
