### PR TITLE
Introduce a new function to simplify parsing arguments

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
@MartyLake: GitHub is still showing commits in a weird order... On the PR creation page, they were ordered as follow:
image
Please start with `Cleanup: Remove unused variable` (https://github.com/McMartin/FRUT/pull/326/commits/2e1d72e61158faddd69eee314efc4e60e07cd010) and use the `Next` button (only available on Desktop) to browse through all the commits.

**Comment by McMartin** [comment]
@MartyLake: I pushed several fixup commits that should fix Travis CI on macOS. Please have a look, thanks!

**Comment by MartyLake** [comment]
Travis is still stalled for the XCode generator :( the fixups look nice to me though

**Comment by McMartin** [comment]
@MartyLake Travis CI is green now. Could you please review?

**Comment by McMartin** [comment]
@MartyLake I rebased this PR on top of the latest master, squashing the fixup commits.

**Comment by McMartin** [comment]
Closing this PR, since I want to introduce these changes in a better way. Stay tuned 📻

**Pull request closed without merging**
