### PR TITLE
Don't let Projucer generate a random ID when loading the Console Application test projects

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Comment by McMartin** [comment]
@MartyLake: this PR is now rebased on top of the latest `master`.

**Comment by MartyLake** [comment]
What is fixed by this pr? I don't understand how these new id's are different from the old ones

**Comment by McMartin** [comment]
The second commit is not important, it is only a consequence of the first commit. Let me know what is not clear with the first commit.

**Comment by McMartin** [comment]
However you're right, this PR is not "fixing" the test projects, since they are not "broken". I should reword the PR title.

**Comment by McMartin** [comment]
Superseded by https://github.com/McMartin/FRUT/pull/419.

**Pull request closed without merging**
