### PR TITLE
Use better way of defining Xcode attributes per configuration

### PR DESCRIPTION
**Pull request by McMartin**
@MartyLake: please review, thanks!

### CODE REVIEW

**Review by MartyLake — APPROVED** [review]
Do you have a link to this `[variant=xx]` notation of CMake ? I have never seen it before.

A quick search engine gave me this json style config https://vector-of-bool.github.io/docs/vscode-cmake-tools/variants.html but that looks different, isn't it ?

Otherwise, LGTM

**Comment by McMartin** [comment]
@MartyLake this behavior is indeed not documented, but you can have a look at the commit that introduced it (https://gitlab.kitware.com/cmake/cmake/-/commit/332350b9c4e6cd198315167664104e645ad3d7ff) or at the state of the code on the latest CMake release at time of writing (https://gitlab.kitware.com/cmake/cmake/-/blob/v3.22.2/Source/cmGlobalXCodeGenerator.cxx#L2104-2134).

**Comment by mtt-ableton** [comment]
@McMartin that's exotic to say the least! how did you ever find out about this ? Do you read cmake's source code daily ?

**Comment by MartyLake** [comment]
@McMartin that's exotic to say the least ! how did you find out about this ?

**Comment by McMartin** [comment]
@MartyLake I made the initial version of this branch more than a year ago, in February 2021, so I don't remember how I found out about this behavior.

**Pull request merged**
